- name: app-setup
  include_role:
    name: common
    tasks_from: app-setup

- name: maven-setup
  include_role:
   name: common
   tasks_from: maven-setup

- name: system-service
  include_role:
   name: common
   tasks_from: system-service

- name: Creating Mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mysql-client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Creating schema
  ansible.builtin.shell: mysql -h mysql.vallalas.store -uroot -pRoboShop@1 < /app/db/schema.sql

- name: creating user
  ansible.builtin.shell: mysql -h mysql.vallalas.store -uroot -pRoboShop@1 < /app/db/app-user.sql 

- name: Loading the data
  ansible.builtin.shell: mysql -h mysql.vallalas.store -uroot -pRoboShop@1 < /app/db/master-data.sql

- name: Shipping service restarted
  ansible.builtin.service:
    name: shipping
    state: restarted