- name: app-setup
  include_role:
   name: common
   tasks_from: app-setup

- name: nodejs-setup
  include_role:
   name: common
   tasks_from: nodejs-setup

- name: system-service
  include_role:
   name: common
   tasks_from: system-service
