- name: copying rabbitmq repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Installing rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: present

- name: Starting and enabling
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Creating rabbitmq user and setting permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    permissions:
    - vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
    state: present