  - name: Installing maven
    ansible.builtin.dnf:
     name: maven
     state: present
  
  - name: Installing dependencies 
    ansible.builtin.command: mvn clean package
    args:
     chdir: /app

  - name: Renaming jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
     chdir: /app