- name: Installing python and dependencies
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - gcc
    - python3-devel


- name: Installing dependencies 
  ansible.builtin.pip:
    requirements: /app/requirements.txt